export const FETCH_IMAGE_LIST = "FETCH_IMAGE_LIST"
export const FETCH_IMAGE_LIST_SUCCESS = "FETCH_IMAGE_LIST_SUCCESS"
export const FETCH_IMAGE_LIST_FAILURE = "FETCH_IMAGE_LIST_FAILURE"

export const FETCH_IMAGE_DETAILS = "FETCH_IMAGE_DETAILS"
export const FETCH_IMAGE_DETAILS_SUCCESS = "FETCH_IMAGE_DETAILS_SUCCESS"
export const FETCH_IMAGE_DETAILS_FAILURE = "FETCH_IMAGE_DETAILS_FAILURE"
